[project]
name = "job-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.70.0",
    "ipykernel>=7.1.0",
    "pydantic-ai>=1.47.0",
]
